/*
Copyright Sponge Projects.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spongeprojects/client-go/api/spongeprojects.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterWatchers implements ClusterWatcherInterface
type FakeClusterWatchers struct {
	Fake *FakeSpongeprojectsV1alpha1
}

var clusterwatchersResource = schema.GroupVersionResource{Group: "spongeprojects.com", Version: "v1alpha1", Resource: "clusterwatchers"}

var clusterwatchersKind = schema.GroupVersionKind{Group: "spongeprojects.com", Version: "v1alpha1", Kind: "ClusterWatcher"}

// Get takes name of the clusterWatcher, and returns the corresponding clusterWatcher object, and an error if there is any.
func (c *FakeClusterWatchers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterwatchersResource, name), &v1alpha1.ClusterWatcher{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterWatcher), err
}

// List takes label and field selectors, and returns the list of ClusterWatchers that match those selectors.
func (c *FakeClusterWatchers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterWatcherList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterwatchersResource, clusterwatchersKind, opts), &v1alpha1.ClusterWatcherList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterWatcherList{ListMeta: obj.(*v1alpha1.ClusterWatcherList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterWatcherList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterWatchers.
func (c *FakeClusterWatchers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterwatchersResource, opts))
}

// Create takes the representation of a clusterWatcher and creates it.  Returns the server's representation of the clusterWatcher, and an error, if there is any.
func (c *FakeClusterWatchers) Create(ctx context.Context, clusterWatcher *v1alpha1.ClusterWatcher, opts v1.CreateOptions) (result *v1alpha1.ClusterWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterwatchersResource, clusterWatcher), &v1alpha1.ClusterWatcher{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterWatcher), err
}

// Update takes the representation of a clusterWatcher and updates it. Returns the server's representation of the clusterWatcher, and an error, if there is any.
func (c *FakeClusterWatchers) Update(ctx context.Context, clusterWatcher *v1alpha1.ClusterWatcher, opts v1.UpdateOptions) (result *v1alpha1.ClusterWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterwatchersResource, clusterWatcher), &v1alpha1.ClusterWatcher{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterWatcher), err
}

// Delete takes name of the clusterWatcher and deletes it. Returns an error if one occurs.
func (c *FakeClusterWatchers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterwatchersResource, name), &v1alpha1.ClusterWatcher{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterWatchers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterwatchersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterWatcherList{})
	return err
}

// Patch applies the patch and returns the patched clusterWatcher.
func (c *FakeClusterWatchers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterWatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterwatchersResource, name, pt, data, subresources...), &v1alpha1.ClusterWatcher{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterWatcher), err
}
