/*
Copyright Sponge Projects.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	spongeprojectscomv1alpha1 "github.com/spongeprojects/client-go/api/spongeprojects.com/v1alpha1"
	versioned "github.com/spongeprojects/client-go/client/clientset/versioned"
	internalinterfaces "github.com/spongeprojects/client-go/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/spongeprojects/client-go/client/listers/spongeprojects.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterWatcherInformer provides access to a shared informer and lister for
// ClusterWatchers.
type ClusterWatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterWatcherLister
}

type clusterWatcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterWatcherInformer constructs a new informer for ClusterWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterWatcherInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterWatcherInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterWatcherInformer constructs a new informer for ClusterWatcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterWatcherInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpongeprojectsV1alpha1().ClusterWatchers().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpongeprojectsV1alpha1().ClusterWatchers().Watch(context.TODO(), options)
			},
		},
		&spongeprojectscomv1alpha1.ClusterWatcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterWatcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterWatcherInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterWatcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&spongeprojectscomv1alpha1.ClusterWatcher{}, f.defaultInformer)
}

func (f *clusterWatcherInformer) Lister() v1alpha1.ClusterWatcherLister {
	return v1alpha1.NewClusterWatcherLister(f.Informer().GetIndexer())
}
