/*
Copyright Sponge Projects.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	spongeprojectscomv1alpha1 "github.com/spongeprojects/client-go/api/spongeprojects.com/v1alpha1"
	versioned "github.com/spongeprojects/client-go/client/clientset/versioned"
	internalinterfaces "github.com/spongeprojects/client-go/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/spongeprojects/client-go/client/listers/spongeprojects.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WatcherInformer provides access to a shared informer and lister for
// Watchers.
type WatcherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.WatcherLister
}

type watcherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWatcherInformer constructs a new informer for Watcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWatcherInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWatcherInformer constructs a new informer for Watcher type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWatcherInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpongeprojectsV1alpha1().Watchers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpongeprojectsV1alpha1().Watchers(namespace).Watch(context.TODO(), options)
			},
		},
		&spongeprojectscomv1alpha1.Watcher{},
		resyncPeriod,
		indexers,
	)
}

func (f *watcherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWatcherInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *watcherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&spongeprojectscomv1alpha1.Watcher{}, f.defaultInformer)
}

func (f *watcherInformer) Lister() v1alpha1.WatcherLister {
	return v1alpha1.NewWatcherLister(f.Informer().GetIndexer())
}
